import { useState } from "react";
import { TbSparkles, TbCopy, TbCheck, TbListCheck, TbDownload } from "react-icons/tb";
import { AiOutlineLoading3Quarters } from "react-icons/ai";
import { streamSummary } from "../utils/api";

const LENGTHS = [
  { key: "short", label: "Short", desc: "3-5 sentences" },
  { key: "medium", label: "Medium", desc: "2-3 paragraphs" },
  { key: "long", label: "Long", desc: "Full breakdown" },
];

async function streamTakeaways(text, docType, onChunk) {
  const res = await fetch("/api/summarize/stream", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      text,
      length: "takeaways",
      doc_type: docType,
    }),
  });

  if (!res.ok) throw new Error("Takeaways failed");

  const reader = res.body.getReader();
  const decoder = new TextDecoder();

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    const chunk = decoder.decode(value, { stream: true });
    onChunk(chunk);
  }
}

function renderText(text) {
  return text.split("\n").map((line, lineIdx) => {
    // Strip markdown headings
    const stripped = line.replace(/^#{1,3}\s+/, "");
    const isHeading = stripped !== line;

    const parts = stripped.split(/\*\*(.*?)\*\*/g);
    const rendered = parts.map((part, i) =>
      i % 2 === 1 ? <strong key={i}>{part}</strong> : part
    );

    return (
      <span key={lineIdx}>
        {isHeading
          ? <strong style={{ fontSize: "15px" }}>{rendered}</strong>
          : rendered}
        {"\n"}
      </span>
    );
  });
}

export default function SummaryPanel({ doc }) {
  const [length, setLength] = useState("medium");
  const [summary, setSummary] = useState("");
  const [takeaways, setTakeaways] = useState([]);
  const [loadingSummary, setLoadingSummary] = useState(false);
  const [loadingTakeaways, setLoadingTakeaways] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");
  const [rawTakeaways, setRawTakeaways] = useState("");

  async function handleSummarize() {
    setLoadingSummary(true);
    setLoadingTakeaways(true);
    setSummary("");
    setTakeaways([]);
    setRawTakeaways("");
    setError("");

    // Stream summary
    try {
      await streamSummary(doc.text, length, doc.doc_type, (chunk) => {
        setSummary((prev) => prev + chunk);
      });
    } catch (e) {
      setError(e.message);
      setLoadingSummary(false);
      setLoadingTakeaways(false);
      return;
    }
    setLoadingSummary(false);

    // Stream takeaways
    try {
      let raw = "";
      await streamTakeaways(doc.text, doc.doc_type, (chunk) => {
        raw += chunk;
        setRawTakeaways(raw);
      });

      // Parse bullet lines
      const lines = raw
        .split("\n")
        .map((l) => l.replace(/^[-•*]\s*/, "").trim())
        .filter((l) => l.length > 10);
      setTakeaways(lines);
    } catch (e) {
      // takeaways failing shouldn't break summary
      console.error("Takeaways error:", e);
    }
    setLoadingTakeaways(false);
  }

  function handleDownload() {
    const filename = doc.filename.replace(/\.[^.]+$/, "") + "_summary.txt";
    const full = [
      `DOCUMENT SUMMARY — ${doc.filename}`,
      `Generated by DocuSense`,
      "",
      "SUMMARY",
      "-------",
      summary,
      ...(takeaways.length ? ["", "KEY TAKEAWAYS", "-------------", ...takeaways.map((t, i) => `${i + 1}. ${t}`)] : []),
    ].join("\n");

    const blob = new Blob([full], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handleCopy() {
    const full = summary + (takeaways.length ? "\n\nKey Takeaways:\n" + takeaways.map(t => `• ${t}`).join("\n") : "");
    await navigator.clipboard.writeText(full);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const loading = loadingSummary || loadingTakeaways;

  return (
    <div style={{
      background: "var(--surface)",
      border: "1px solid var(--border)",
      borderRadius: "12px",
      overflow: "hidden",
    }}>
      {/* Header */}
      <div style={{
        padding: "16px 20px",
        borderBottom: "1px solid var(--border)",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        flexWrap: "wrap",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <TbSparkles size={16} color="var(--accent)" />
          <span style={{ fontWeight: 600, fontSize: "14px" }}>Summary</span>
        </div>

        <div style={{
          display: "flex",
          background: "var(--surface-2)",
          borderRadius: 8,
          padding: 3,
          gap: 2,
        }}>
          {LENGTHS.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setLength(key)}
              style={{
                padding: "5px 14px",
                borderRadius: 6,
                border: "none",
                background: length === key ? "var(--accent)" : "transparent",
                color: length === key ? "#fff" : "var(--text-muted)",
                fontSize: "13px",
                fontWeight: length === key ? 600 : 400,
                cursor: "pointer",
                transition: "all 0.15s ease",
              }}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Content */}
      <div style={{ padding: "20px" }}>
        {!summary && !loading && (
          <div style={{ textAlign: "center", padding: "24px 0" }}>
            <p style={{ color: "var(--text-muted)", fontSize: "14px", marginBottom: 16 }}>
              Choose a summary length and generate
            </p>
            <button
              onClick={handleSummarize}
              style={{
                background: "var(--accent)",
                color: "#fff",
                border: "none",
                borderRadius: 8,
                padding: "10px 24px",
                fontSize: "14px",
                fontWeight: 600,
                cursor: "pointer",
              }}
            >
              Generate Summary
            </button>
          </div>
        )}

        {loadingSummary && !summary && (
          <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--text-muted)", padding: "8px 0" }}>
            <AiOutlineLoading3Quarters size={14} style={{ animation: "spin 1s linear infinite" }} />
            <span style={{ fontSize: "13px" }}>Generating summary...</span>
          </div>
        )}

        {summary && (
          <>
            <p style={{ lineHeight: 1.75, fontSize: "14px", color: "var(--text)" }}>
              {renderText(summary)}
              {loadingSummary && (
                <span style={{
                  display: "inline-block",
                  width: 2,
                  height: "1em",
                  background: "var(--accent)",
                  marginLeft: 2,
                  verticalAlign: "middle",
                  animation: "blink 1s step-end infinite",
                }} />
              )}
            </p>

            {/* Takeaways */}
            {(loadingTakeaways || takeaways.length > 0) && (
              <div style={{
                marginTop: 20,
                background: "var(--surface-2)",
                border: "1px solid var(--border)",
                borderRadius: 10,
                padding: "14px 16px",
              }}>
                <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 10 }}>
                  <TbListCheck size={14} color="var(--accent)" />
                  <span style={{ fontSize: "12px", fontWeight: 600, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.05em" }}>
                    Key Takeaways
                  </span>
                </div>

                {loadingTakeaways && takeaways.length === 0 && (
                  <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--text-muted)" }}>
                    <AiOutlineLoading3Quarters size={12} style={{ animation: "spin 1s linear infinite" }} />
                    <span style={{ fontSize: "13px" }}>Extracting key points...</span>
                  </div>
                )}

                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 }}>
                  {takeaways.map((point, i) => (
                    <li key={i} style={{ display: "flex", gap: 10, fontSize: "13px", lineHeight: 1.6 }}>
                      <span style={{
                        width: 18,
                        height: 18,
                        borderRadius: "50%",
                        background: "var(--accent-dim)",
                        color: "var(--accent)",
                        fontSize: "11px",
                        fontWeight: 700,
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        flexShrink: 0,
                        marginTop: 2,
                      }}>
                        {i + 1}
                      </span>
                      <span>{renderText(point)}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {!loading && (
              <div style={{ display: "flex", gap: 10, marginTop: 16 }}>
                <button
                  onClick={handleCopy}
                  style={{
                    display: "flex", alignItems: "center", gap: 6,
                    padding: "7px 14px", borderRadius: 7,
                    border: "1px solid var(--border)", background: "transparent",
                    color: copied ? "var(--success)" : "var(--text-muted)",
                    fontSize: "13px", cursor: "pointer",
                  }}
                >
                  {copied ? <TbCheck size={13} /> : <TbCopy size={13} />}
                  {copied ? "Copied!" : "Copy"}
                </button>
                <button
                  onClick={handleDownload}
                  style={{
                    display: "flex", alignItems: "center", gap: 6,
                    padding: "7px 14px", borderRadius: 7,
                    border: "1px solid var(--border)", background: "transparent",
                    color: "var(--text-muted)",
                    fontSize: "13px", cursor: "pointer",
                  }}
                >
                  <TbDownload size={13} />
                  Export
                </button>
                <button
                  onClick={handleSummarize}
                  style={{
                    display: "flex", alignItems: "center", gap: 6,
                    padding: "7px 14px", borderRadius: 7,
                    border: "1px solid var(--border)", background: "transparent",
                    color: "var(--text-muted)", fontSize: "13px", cursor: "pointer",
                  }}
                >
                  <TbSparkles size={13} />
                  Regenerate
                </button>
              </div>
            )}
          </>
        )}

        {error && (
          <p style={{ color: "var(--error)", fontSize: "13px", marginTop: 8 }}>{error}</p>
        )}
      </div>

      <style>{`
        @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}
